(define training-sentences (list

(list (list "Bring"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "my"	"PRP$"	"Object"	"AA")
(list "food"	"NN"	"Object"	"AA")
(list "delivery"	"NN"	"Object"	"AA")
(list "from"	"IN"	"FromLocation"	"AA")
(list "the"	"DT"	"FromLocation"	"AA")
(list "fourth"	"JJ"	"FromLocation"	"AA")
(list "floor"	"NN"	"FromLocation"	"AA")
(list "entrance"	"NN"	"FromLocation"	"AA")
)
(list
(list "Bring"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "some"	"DT"	"Object"	"AA")
(list "coffee"	"NN"	"Object"	"AA")
(list "from"	"IN"	"FromLocation"	"VV")
(list "the"	"DT"	"FromLocation"	"VV")
(list "kitchen"	"NN"	"FromLocation"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "from"	"IN"	"FromLocation"	"VV")
(list "the"	"DT"	"FromLocation"	"VV")
(list "coffee"	"NN"	"FromLocation"	"VV")
(list "shop"	"NN"	"FromLocation"	"VV")
)
(list
(list "Take"	"VB"	"Action"	"AA")
(list "the"	"DT"	"Object"	"AA")
(list "visiting"	"VBG"	"Object"	"AA")
(list "student"	"NN"	"Object"	"AA")
(list "from"	"IN"	"FromLocation"	"AA")
(list "Manuela's"	"JJ"	"FromLocation"	"AA")
(list "office"	"NN"	"FromLocation"	"AA")
(list "to"	"TO"	"ToLocation"	"AA")
(list "the"	"DT"	"ToLocation"	"AA")
(list "kitchen"	"NN"	"ToLocation"	"AA")
)
(list
(list "Bring"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "a"	"DT"	"Object"	"VV")
(list "coffee"	"NN"	"Object"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "a"	"DT"	"Object"	"VV")
(list "hot"	"JJ"	"Object"	"VV")
(list "chocolate"	"NN"	"Object"	"VV")
)
(list
(list "Go"	"VB"	"Action"	"AA")
(list "to"	"TO"	"ToLocation"	"AA")
(list "the"	"DT"	"ToLocation"	"AA")
(list "lounge"	"NN"	"ToLocation"	"AA")
)
(list
(list "Pick"	"VB"	"Action"	"&&")
(list "up"	"RP"	"Action"	"&&")
(list "a"	"DT"	"Object"	"&&")
(list "sandwich"	"NN"	"Object"	"&&")
(list "from"	"IN"	"FromLocation"	"&&")
(list "the"	"DT"	"FromLocation"	"&&")
(list "kitchen"	"NN"	"FromLocation"	"&&")
(list "and"	"CC"	"And"	"N")
(list "deliver"	"VB"	"Action"	"&&")
(list "it"	"PRP"	"Pronoun"	"&&")
(list "to"	"TO"	"None"	"&&")
(list "Christina"	"NNP"	"Person"	"&&")
)
(list
(list "Bring"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "a"	"DT"	"Object"	"&&")
(list "cookie"	"NN"	"Object"	"&&")
(list "from"	"IN"	"FromLocation"	"&&")
(list "the"	"DT"	"FromLocation"	"&&")
(list "kitchen"	"NN"	"FromLocation"	"&&")
(list "and"	"CC"	"And"	"N")
(list "one"	"CD"	"Pronoun"	"&&")
(list "from"	"IN"	"FromLocation"	"&&")
(list "the"	"DT"	"FromLocation"	"&&")
(list "coffee"	"NN"	"FromLocation"	"&&")
(list "shop"	"NN"	"FromLocation"	"&&")
)
(list
(list "Go"	"VB"	"Action"	"AA")
(list "to"	"TO"	"ToLocation"	"&&")
(list "the"	"DT"	"ToLocation"	"&&")
(list "kitchen"	"NN"	"ToLocation"	"&&")
(list "and"	"CC"	"And"	"N")
(list "the"	"DT"	"ToLocation"	"&&")
(list "bathroom"	"NN"	"ToLocation"	"&&")
)
(list
(list "Go"	"VB"	"Action"	"AA")
(list "to"	"TO"	"ToLocation"	"AA")
(list "the"	"DT"	"ToLocation"	"AA")
(list "lab"	"NN"	"ToLocation"	"AA")
)
(list
(list "Bring"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "a"	"DT"	"Object"	"VV")
(list "pen"	"NN"	"Object"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "a"	"DT"	"Object"	"VV")
(list "pencil"	"NN"	"Object"	"VV")
)
(list
(list "Take"	"VB"	"Action"	"AA")
(list "my"	"PRP$"	"Object"	"AA")
(list "paper"	"NN"	"Object"	"AA")
(list "from"	"IN"	"FromLocation"	"AA")
(list "the"	"DT"	"FromLocation"	"AA")
(list "lab"	"NN"	"FromLocation"	"AA")
(list "to"	"TO"	"ToLocation"	"AA")
(list "Manuela's"	"NN"	"ToLocation"	"AA")
(list "office"	"NN"	"ToLocation"	"AA")
)
(list
(list "Go"	"VB"	"Action"	"AA")
(list "to"	"TO"	"ToLocation"	"VV")
(list "the"	"DT"	"ToLocation"	"VV")
(list "lab"	"NN"	"ToLocation"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "the"	"DT"	"ToLocation"	"VV")
(list "kitchen"	"NN"	"ToLocation"	"VV")
)
(list
(list "Go"	"VB"	"Action"	"&&")
(list "to"	"TO"	"ToLocation"	"&&")
(list "the"	"DT"	"ToLocation"	"&&")
(list "lab"	"NN"	"ToLocation"	"&&")
(list "then"	"RB"	"And"	"N")
(list "go"	"VB"	"Action"	"&&")
(list "to"	"TO"	"ToLocation"	"&&")
(list "the"	"DT"	"ToLocation"	"&&")
(list "meeting"	"NN"	"ToLocation"	"&&")
(list "room"	"NN"	"ToLocation"	"&&")
)
(list
(list "Go"	"VB"	"Action"	"&&")
(list "to"	"TO"	"ToLocation"	"&&")
(list "the"	"DT"	"ToLocation"	"&&")
(list "lab"	"NN"	"ToLocation"	"&&")
(list "and"	"CC"	"And"	"N")
(list "bring"	"VB"	"Action"	"&&")
(list "me"	"PRP"	"Action"	"&&")
(list "a"	"DT"	"Object"	"&&")
(list "robot"	"NN"	"Object"	"&&")
)
(list
(list "Go"	"VB"	"Action"	"AA")
(list "to"	"TO"	"ToLocation"	"&&")
(list "the"	"DT"	"ToLocation"	"&&")
(list "kitchen"	"NN"	"ToLocation"	"&&")
(list "and"	"CC"	"And"	"N")
(list "the"	"DT"	"ToLocation"	"&&")
(list "conference"	"NN"	"ToLocation"	"&&")
(list "room"	"NN"	"ToLocation"	"&&")
)
(list
(list "Please"	"VB"	"None"	"N")
(list "go"	"VB"	"Action"	"AA")
(list "to"	"TO"	"ToLocation"	"AA")
(list "my"	"PRP$"	"ToLocation"	"AA")
(list "office"	"NN"	"ToLocation"	"AA")
)
(list
(list "Please"	"VB"	"None"	"N")
(list "bring"	"VB"	"Action"	"AA")
(list "these"	"DT"	"Person"	"AA")
(list "guests"	"NNS"	"Person"	"AA")
(list "to"	"TO"	"ToLocation"	"AA")
(list "the"	"DT"	"ToLocation"	"AA")
(list "lab"	"NN"	"ToLocation"	"AA")
)
(list
(list "Please"	"VB"	"None"	"N")
(list "pick"	"VB"	"Action"	"&&")
(list "up"	"RP"	"Action"	"&&")
(list "a"	"DT"	"Object"	"&&")
(list "form"	"NN"	"Object"	"&&")
(list "from"	"IN"	"FromLocation"	"&&")
(list "the"	"DT"	"FromLocation"	"&&")
(list "lab"	"NN"	"FromLocation"	"&&")
(list "and"	"CC"	"And"	"N")
(list "then"	"PRP"	"And"	"N")
(list "bring"	"VBP"	"Action"	"&&")
(list "it"	"PRP"	"Pronoun"	"&&")
(list "to"	"TO"	"ToLocation"	"&&")
(list "my"	"PRP$"	"ToLocation"	"&&")
(list "office"	"NN"	"ToLocation"	"&&")
)
(list
(list "Go"	"VB"	"Action"	"AA")
(list "to"	"TO"	"ToLocation"	"AA")
(list "the"	"DT"	"ToLocation"	"AA")
(list "lab"	"NN"	"ToLocation"	"AA")
)
(list
(list "Please"	"VB"	"None"	"N")
(list "go"	"VB"	"Action"	"&&")
(list "to"	"TO"	"ToLocation"	"&&")
(list "the"	"DT"	"ToLocation"	"&&")
(list "lab"	"NN"	"ToLocation"	"&&")
(list "and"	"CC"	"And"	"N")
(list "pick"	"VB"	"Action"	"&&")
(list "up"	"RP"	"Action"	"&&")
(list "a"	"DT"	"Object"	"&&")
(list "form"	"NN"	"Object"	"&&")
)
(list
(list "Robot"	"NN"	"None"	"N")
(list "bring"	"VBP"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "a"	"DT"	"Object"	"AA")
(list "beer"	"NN"	"Object"	"AA")
)
(list
(list "go"	"VB"	"Action"	"AA")
(list "to"	"TO"	"ToLocation"	"AA")
(list "the"	"DT"	"ToLocation"	"AA")
(list "lab"	"NN"	"ToLocation"	"AA")
)
(list
(list "bring"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "either"	"CC"	"Or"	"N")
(list "a"	"DT"	"Object"	"VV")
(list "coke"	"NN"	"Object"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "a"	"DT"	"Object"	"VV")
(list "coffee"	"NN"	"Object"	"VV")
)
(list
(list "get"	"VB"	"Action"	"AA")
(list "to"	"TO"	"ToLocation"	"VV")
(list "the"	"DT"	"ToLocation"	"VV")
(list "printer"	"NN"	"ToLocation"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "the"	"DT"	"ToLocation"	"VV")
(list "cafeteria"	"NN"	"ToLocation"	"VV")
)
(list
(list "get"	"VB"	"Action"	"&&")
(list "to"	"TO"	"ToLocation"	"&&")
(list "the"	"DT"	"ToLocation"	"&&")
(list "lab"	"NN"	"ToLocation"	"&&")
(list "and"	"CC"	"And"	"N")
(list "fetch"	"VB"	"Action"	"&&")
(list "a"	"DT"	"Object"	"&&")
(list "book"	"NN"	"Object"	"&&")
)
(list
(list "get"	"VB"	"Action"	"&&")
(list "the"	"DT"	"Object"	"&&")
(list "AI"	"NNP"	"Object"	"&&")
(list "book"	"NN"	"Object"	"&&")
(list "in"	"IN"	"FromLocation"	"&&")
(list "the"	"DT"	"FromLocation"	"&&")
(list "lab"	"NN"	"FromLocation"	"&&")
(list "and"	"CC"	"And"	"N")
(list "bring"	"VB"	"Action"	"&&")
(list "it"	"PRP"	"Pronoun"	"&&")
(list "to"	"TO"	"ToLocation"	"&&")
(list "the"	"DT"	"ToLocation"	"&&")
(list "professor"	"NN"	"ToLocation"	"&&")
)
(list
(list "fetch"	"VB"	"Action"	"AA")
(list "a"	"DT"	"Object"	"&&")
(list "beer"	"NN"	"Object"	"&&")
(list "and"	"CC"	"And"	"N")
(list "a"	"DT"	"Object"	"&&")
(list "coke"	"NN"	"Object"	"&&")
)
(list
(list "Can"	"MD"	"None"	"N")
(list "you"	"PRP"	"None"	"N")
(list "bring"	"VB"	"Action"	"AA")
(list "my"	"PRP$"	"Object"	"AA")
(list "mail"	"NN"	"Object"	"AA")
(list "from"	"IN"	"FromLocation"	"AA")
(list "the"	"DT"	"FromLocation"	"AA")
(list "6th"	"JJ"	"FromLocation"	"AA")
(list "floor"	"NN"	"FromLocation"	"AA")
)
(list
(list "Can"	"MD"	"None"	"N")
(list "you"	"PRP"	"None"	"N")
(list "get"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "some"	"DT"	"Object"	"VV")
(list "coffee"	"NN"	"Object"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "tea"	"NN"	"Object"	"VV")
)
(list
(list "Please"	"VB"	"None"	"N")
(list "pick"	"VB"	"Action"	"&&")
(list "up"	"RP"	"Action"	"&&")
(list "the"	"DT"	"Object"	"&&")
(list "keys"	"NNS"	"Object"	"&&")
(list "from"	"IN"	"None"	"&&")
(list "Christina"	"NNP"	"Person"	"&&")
(list "and"	"CC"	"And"	"N")
(list "give"	"VB"	"Action"	"&&")
(list "them"	"PRP"	"Pronoun"	"&&")
(list "to"	"TO"	"None"	"&&")
(list "Vittorio"	"NNP"	"Person"	"&&")
)
(list
(list "Can"	"MD"	"None"	"N")
(list "you"	"PRP"	"None"	"N")
(list "get"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "some"	"DT"	"Object"	"&&")
(list "tea"	"NN"	"Object"	"&&")
(list "and"	"CC"	"And"	"N")
(list "cookies"	"NNS"	"Object"	"&&")
)
(list
(list "Can"	"MD"	"None"	"N")
(list "you"	"PRP"	"None"	"N")
(list "get"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "some"	"DT"	"Object"	"AA")
(list "coffee"	"NN"	"Object"	"AA")
(list "with"	"IN"	"Object"	"AA")
(list "cream"	"NN"	"Object"	"AA")
)
(list
(list "Please"	"VB"	"None"	"N")
(list "get"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "a"	"DT"	"Object"	"&&")
(list "cup"	"NN"	"Object"	"&&")
(list "of"	"IN"	"Object"	"&&")
(list "hot"	"JJ"	"Object"	"&&")
(list "chocolate"	"NN"	"Object"	"&&")
(list "and"	"CC"	"And"	"N")
(list "some"	"DT"	"Object"	"&&")
(list "snacks"	"NNS"	"Object"	"&&")
(list "as"	"RB"	"None"	"&&")
(list "well"	"RB"	"None"	"&&")
)
(list
(list "Please"	"VB"	"None"	"N")
(list "go"	"VB"	"Action"	"VV")
(list "and"	"CC"	"Action"	"VV")
(list "fetch"	"VB"	"Action"	"VV")
(list "me"	"PRP"	"Action"	"VV")
(list "today's"	"FW"	"Object"	"VV")
(list "newspaper"	"NN"	"Object"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "get"	"VB"	"Action"	"VV")
(list "me"	"PRP"	"Action"	"VV")
(list "a"	"DT"	"Object"	"VV")
(list "cup"	"NN"	"Object"	"VV")
(list "of"	"IN"	"Object"	"VV")
(list "coffee"	"NN"	"Object"	"VV")
)
(list
(list "Bring"	"VB"	"Action"	"AA")
(list "this"	"DT"	"Object"	"&&")
(list "yellow"	"JJ"	"Object"	"&&")
(list "envelope"	"NN"	"Object"	"&&")
(list "to"	"TO"	"ToLocation"	"&&")
(list "GHC3201"	"NN"	"ToLocation"	"&&")
(list "and"	"CC"	"And"	"N")
(list "the"	"DT"	"Object"	"&&")
(list "red"	"JJ"	"Object"	"&&")
(list "envelope"	"NN"	"Object"	"&&")
(list "to"	"TO"	"ToLocation"	"&&")
(list "GHC7002"	"NN"	"ToLocation"	"&&")
)
(list
(list "Either"	"NNP"	"Or"	"N")
(list "deliver"	"VB"	"Action"	"VV")
(list "this"	"DT"	"Object"	"VV")
(list "yellow"	"JJ"	"Object"	"VV")
(list "envelope"	"NN"	"Object"	"VV")
(list "first"	"RB"	"None"	"VV")
(list "to"	"TO"	"ToLocation"	"VV")
(list "GHC3201"	"NN"	"ToLocation"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "deliver"	"VB"	"Action"	"VV")
(list "this"	"DT"	"Object"	"VV")
(list "red"	"JJ"	"Object"	"VV")
(list "envelope"	"NN"	"Object"	"VV")
(list "first"	"RB"	"None"	"VV")
(list "to"	"TO"	"ToLocation"	"VV")
(list "GHC7002"	"NN"	"ToLocation"	"VV")
)
(list
(list "Take"	"VB"	"Action"	"&&")
(list "this"	"DT"	"Object"	"&&")
(list "envelope"	"NN"	"Object"	"&&")
(list "to"	"TO"	"ToLocation"	"&&")
(list "GHC3201"	"NN"	"ToLocation"	"&&")
(list "and"	"CC"	"And"	"N")
(list "get"	"VB"	"Action"	"&&")
(list "me"	"PRP"	"Action"	"&&")
(list "a"	"DT"	"Object"	"&&")
(list "cup"	"NN"	"Object"	"&&")
(list "of"	"IN"	"Object"	"&&")
(list "coffee"	"NN"	"Object"	"&&")
)
(list
(list "Get"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "a"	"DT"	"Object"	"&&")
(list "cup"	"NN"	"Object"	"&&")
(list "of"	"IN"	"Object"	"&&")
(list "coffee"	"NN"	"Object"	"&&")
(list "and"	"CC"	"And"	"NN")
(list "the"	"DT"	"Object"	"&&")
(list "newspaper"	"NN"	"Object"	"&&")
)
(list
(list "Bring"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "today's"	"FW"	"Object"	"&&")
(list "newspaper"	"NN"	"Object"	"&&")
(list "and"	"CC"	"And"	"N")
(list "a"	"DT"	"Object"	"&&")
(list "cup"	"NN"	"Object"	"&&")
(list "of"	"IN"	"Object"	"&&")
(list "hot"	"JJ"	"Object"	"&&")
(list "chocolate"	"NN"	"Object"	"&&")
)
(list
(list "Robot"	"NN"	"None"	"N")
(list "please"	"VBP"	"None"	"N")
(list "deliver"	"VB"	"Action"	"AA")
(list "this"	"DT"	"Object"	"AA")
(list "document"	"NN"	"Object"	"AA")
(list "to"	"TO"	"None"	"VV")
(list "Mr"	"NNP"	"Person"	"VV")
(list "Brown"	"NNP"	"Person"	"VV")
(list "at"	"IN"	"ToLocation"	"VV")
(list "office"	"NN"	"ToLocation"	"VV")
(list "201"	"CD"	"ToLocation"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "Mr"	"NNP"	"Person"	"VV")
(list "Black"	"NNP"	"Person"	"VV")
(list "at"	"IN"	"ToLocation"	"VV")
(list "office"	"NN"	"ToLocation"	"VV")
(list "123"	"CD"	"ToLocation"	"VV")
)
(list
(list "Robot"	"NN"	"None"	"N")
(list "please"	"VBP"	"None"	"N")
(list "find"	"VB"	"Action"	"AA")
(list "an"	"DT"	"Object"	"VV")
(list "umbrella"	"NN"	"Object" 	"VV")
(list "or"	"CC"	"Or"	"N")
(list "a"	"DT"	"Object"	"VV")
(list "raincoat"	"NN"	"Object"	"VV")
)
(list
(list "Robot"	"NN"	"None"	"N")
(list "please"	"VBP"	"None"	"N")
(list "bring"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "a"	"DT"	"Object"	"VV")
(list "coffee"	"NN"	"Object"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "an"	"DT"	"Object"	"VV")
(list "orange"	"JJ"	"Object"	"VV")
(list "juice"	"NN"	"Object"	"VV")
)
(list
(list "Robot"	"NN"	"None"	"N")
(list "go"	"VB"	"Action"	"&&")
(list "to"	"TO"	"ToLocation"	"&&")
(list "the"	"DT"	"ToLocation"	"&&")
(list "technical"	"JJ"	"ToLocation"	"&&")
(list "office"	"NN"	"ToLocation"	"&&")
(list "and"	"CC"	"And"	"N")
(list "take"	"VB"	"Action"	"&&")
(list "the"	"DT"	"Object"	"&&")
(list "document"	"NN"	"Object"	"&&")
(list "from"	"IN"	"FromLocation"	"&&")
(list "the"	"DT"	"FromLocation"	"&&")
(list "printer"	"NN"	"FromLocation"	"&&")
)
(list
(list "Robot"	"NN"	"None"	"N")
(list "please"	"VBP"	"None"	"N")
(list "take"	"NN"	"Action"	"AA")
(list "from"	"IN"	"FromLocation"	"AA")
(list "the"	"DT"	"FromLocation"	"AA")
(list "bookshelf"	"NN"	"FromLocation"	"AA")
(list "all"	"PDT"	"Object"	"&&")
(list "the"	"DT"	"Object"	"&&")
(list "yellow"	"JJ"	"Object"	"&&")
(list "books"	"NNS"	"Object"	"&&")
(list "and"	"CC"	"And"	"N")
(list "all"	"PDT"	"Object"	"&&")
(list "the"	"DT"	"Object"	"&&")
(list "red"	"JJ"	"Object"	"&&")
(list "books"	"NNS"	"Object"	"&&")
)
(list
(list "Please"	"VB"	"None"	"N")
(list "get"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "pizza"	"NN"	"Object"	"AA")
(list "from"	"IN"	"FromLocation"	"VV")
(list "the"	"DT"	"FromLocation"	"VV")
(list "kitchen"	"NN"	"FromLocation"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "from"	"IN"	"FromLocation"	"VV")
(list "the"	"DT"	"FromLocation"	"VV")
(list "conference"	"NN"	"FromLocation"	"VV")
(list "room"	"NN"	"FromLocation"	"VV")
)
(list
(list "Take"	"VB"	"Action"	"AA")
(list "this"	"DT"	"Object"	"AA")
(list "paper"	"NN"	"Object"	"AA")
(list "to"	"TO"	"ToLocation"	"AA")
(list "the"	"DT"	"ToLocation"	"AA")
(list "lab"	"NN"	"ToLocation"	"AA")
)
(list
(list "Get"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "pizza"	"NN"	"Object"	"AA")
(list "from"	"IN"	"FromLocation"	"VV")
(list "the"	"DT"	"FromLocation"	"VV")
(list "lab"	"NN"	"FromLocation"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "from"	"IN"	"FromLocation"	"VV")
(list "the"	"DT"	"FromLocation"	"VV")
(list "conference"	"NN"	"FromLocation"	"VV")
(list "room"	"NN"	"FromLocation"	"VV")
)
(list
(list "Please"	"VB"	"None"	"N")
(list "either"	"CC"	"Or"	"N")
(list "go"	"VB"	"Action"	"VV")
(list "to"	"TO"	"ToLocation"	"VV")
(list "the"	"DT"	"ToLocation"	"VV")
(list "lab"	"NN"	"ToLocation"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "come"	"VBN"	"Action"	"VV")
(list "to"	"TO"	"ToLocation"	"VV")
(list "my"	"PRP$"	"ToLocation"	"VV")
(list "office"	"NN"	"ToLocation"	"VV")
)
(list
(list "Please"	"VB"	"None"	"N")
(list "go"	"VB"	"Action"	"&&")
(list "to"	"TO"	"ToLocation"	"&&")
(list "the"	"DT"	"ToLocation"	"&&")
(list "lab"	"NN"	"ToLocation"	"&&")
(list "and"	"CC"	"And"	"N")
(list "then"	"RB"	"And"	"N")
(list "come"	"VB"	"Action"	"&&")
(list "back"	"RB"	"Action"	"&&")
)
(list
(list "Bring"	"VB"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "a"	"DT"	"Object"	"&&")
(list "cup"	"NN"	"Object"	"&&")
(list "and"	"CC"	"And"	"N")
(list "an"	"DT"	"Object"	"&&")
(list "apple"	"NN"	"Object"	"&&")
(list "tart"	"JJ"	"Object"	"&&")
)
(list
(list "Go"	"VB"	"Action"	"VV")
(list "to"	"TO"	"ToLocation"	"VV")
(list "the"	"DT"	"ToLocation"	"VV")
(list "office"	"NN"	"ToLocation"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "bring"	"VB"	"Action"	"VV")
(list "me"	"PRP"	"Action"	"VV")
(list "a"	"DT"	"Object"	"VV")
(list "paper"	"NN"	"Object"	"VV")
)
(list
(list "Go"	"VB"	"Action"	"AA")
(list "to"	"TO"	"ToLocation"	"VV")
(list "the"	"DT"	"ToLocation"	"VV")
(list "office"	"NN"	"ToLocation"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "to"	"TO"	"ToLocation"	"VV")
(list "the"	"DT"	"ToLocation"	"VV")
(list "bathroom"	"NN"	"ToLocation"	"VV")
)
(list
(list "Bring"	"VB"	"Action"	"AA")
(list "to"	"TO"	"Action"	"AA")
(list "me"	"PRP"	"Action"	"AA")
(list "a"	"DT"	"Object"	"VV")
(list "pen"	"NN"	"Object"	"VV")
(list "or"	"CC"	"Or"	"N")
(list "a"	"DT"	"Object"	"VV")
(list "paper"	"NN"	"Object"	"VV")
)
(list
(list "Go"	"VB"	"Action"	"&&")
(list "to"	"TO"	"ToLocation"	"&&")
(list "the"	"DT"	"ToLocation"	"&&")
(list "table"	"NN"	"ToLocation"	"&&")
(list "and"	"CC"	"And"	"N")
(list "then"	"RB"	"And"	"N")
(list "check"	"VB"	"Action"	"&&")
(list "for"	"IN"	"Action"	"&&")
(list "a"	"DT"	"Object"	"&&")
(list "book"	"NN"	"Object"	"&&")
)
(list
(list "Bring"	"VB"	"Action"	"&&")
(list "me"	"PRP"	"Action"	"&&")
(list "a"	"DT"	"Object"	"&&")
(list "book"	"NN"	"Object"	"&&")
(list "and"	"CC"	"And"	"N")
(list "then"	"RB"	"And"	"N")
(list "bring"	"VB"	"Action"	"&&")
(list "me"	"PRP"	"Action"	"&&")
(list "a"	"DT"	"Object"	"&&")
(list "pen"	"NN"	"Object"	"&&")
)
(list
(list "Check"	"VB"	"Action"	"AA")
(list "for"	"IN"	"Action"	"AA")
(list "a"	"DT"	"Object"	"&&")
(list "paper"	"NN"	"Object"	"&&")
(list "and"	"CC"	"And"	"N")
(list "a"	"DT"	"Object"	"&&")
(list "pen"	"NN"	"Object"	"&&")
)
))
